export interface IssueRow {
  number: string;
  date: string;
  title: string;
  dek: string;
  topic: string;
  region: string;
  access: "free" | "premium";
  readTime: string;
  slug?: string;
  searchTerms: string;
}

export const TOPICS = [
  "Corporate Tax",
  "Consumption Tax",
  "Cross-Border",
  "Tax Economics",
  "Compliance",
] as const;

export const REGIONS = [
  "Europe",
  "Middle East",
  "Nordics",
  "Asia",
  "Americas",
  "UK",
  "Global",
] as const;

export const ISSUES: IssueRow[] = [
  {
    number: "№ 27",
    date: "Jun 5, 2026",
    title: "The country that taxes profit only when you take it out",
    dek: "Estonia charges 0% on profit you reinvest and 22% the moment you distribute it — the system founders everywhere keep citing, with the data behind it.",
    topic: "Corporate Tax",
    region: "Europe",
    access: "free",
    readTime: "6 min",
    slug: "estonia-distribution-tax",
    searchTerms: "estonia distribution tax profit reinvest corporate",
  },
  {
    number: "№ 26",
    date: "May 29, 2026",
    title: "Why the tax year starts in April",
    dek: "Blame an 18th-century calendar bug nobody ever fixed. A short, true, slightly absurd story.",
    topic: "Compliance",
    region: "UK",
    access: "free",
    readTime: "5 min",
    searchTerms: "why tax year starts april calendar",
  },
  {
    number: "№ 25",
    date: "May 22, 2026",
    title: "Carbon border taxes arrive in Europe",
    dek: "A primer for exporters on CBAM — the levy that taxes the carbon baked into what crosses the border.",
    topic: "Tax Economics",
    region: "Europe",
    access: "free",
    readTime: "7 min",
    searchTerms: "carbon border tax cbam europe exporters",
  },
  {
    number: "№ 24",
    date: "May 15, 2026",
    title: "Digital nomad visas are a tax trap dressed as a beach",
    dek: "The residency rules the brochures skip — and how a year abroad can quietly land you two tax bills.",
    topic: "Cross-Border",
    region: "Global",
    access: "premium",
    readTime: "8 min",
    searchTerms: "digital nomad visa tax trap residency",
  },
  {
    number: "№ 23",
    date: "May 8, 2026",
    title: "VAT, GST & sales tax: one idea, three headaches",
    dek: "They all tax consumption — and behave nothing alike. A field guide for anyone selling across a border.",
    topic: "Consumption Tax",
    region: "Global",
    access: "free",
    readTime: "6 min",
    searchTerms: "vat gst sales tax consumption difference",
  },
  {
    number: "№ 22",
    date: "May 1, 2026",
    title: "The global minimum tax, in human language",
    dek: "Pillar Two sounds like flat-pack furniture. It's really a 15% floor under the world's biggest companies.",
    topic: "Tax Economics",
    region: "Global",
    access: "free",
    readTime: "7 min",
    searchTerms: "global minimum tax pillar two 15 percent multinational",
  },
  {
    number: "№ 21",
    date: "Apr 24, 2026",
    title: "The end of the zero-tax dream? The UAE's new 9%",
    dek: "A region built on no income tax introduces a corporate levy. What changes for founders and free zones.",
    topic: "Corporate Tax",
    region: "Middle East",
    access: "free",
    readTime: "7 min",
    searchTerms: "uae 9 percent corporate tax gulf zero",
  },
  {
    number: "№ 20",
    date: "Apr 17, 2026",
    title: "Norway's exit tax and the founders leaving",
    dek: "What the headlines miss about wealth, mobility, and the real numbers behind the great departure.",
    topic: "Cross-Border",
    region: "Nordics",
    access: "premium",
    readTime: "8 min",
    searchTerms: "norway exit tax founders leaving wealth",
  },
  {
    number: "№ 19",
    date: "Apr 10, 2026",
    title: "Singapore's territorial system, and the exemption founders miss",
    dek: "A headline 17% that almost nobody pays in year one. The partial exemption, explained with the math.",
    topic: "Corporate Tax",
    region: "Asia",
    access: "premium",
    readTime: "8 min",
    searchTerms: "singapore territorial system exemption startup",
  },
  {
    number: "№ 18",
    date: "Apr 3, 2026",
    title: "Ireland's 12.5%, and the machinery behind it",
    dek: "How a small rate plus a clever base turned one country into the HQ of half the software you use.",
    topic: "Corporate Tax",
    region: "Europe",
    access: "premium",
    readTime: "8 min",
    searchTerms: "ireland 12.5 percent ip software headquarters",
  },
  {
    number: "№ 17",
    date: "Mar 27, 2026",
    title: "Depreciation, but make it geopolitics",
    dek: "How write-off schedules quietly steer where the world builds its factories. Tax as industrial policy.",
    topic: "Tax Economics",
    region: "Global",
    access: "premium",
    readTime: "7 min",
    searchTerms: "depreciation industrial policy write-off factories",
  },
  {
    number: "№ 16",
    date: "Mar 20, 2026",
    title: "The EU VAT One-Stop-Shop, explained",
    dek: "One registration to sell across 27 countries — the rule that made cross-border e-commerce bearable.",
    topic: "Consumption Tax",
    region: "Europe",
    access: "free",
    readTime: "6 min",
    searchTerms: "eu vat one stop shop oss ecommerce",
  },
  {
    number: "№ 15",
    date: "Mar 13, 2026",
    title: "Effective vs headline: the rate that actually matters",
    dek: "A worked example across three jurisdictions showing why the press-release number is rarely what you pay.",
    topic: "Corporate Tax",
    region: "Global",
    access: "premium",
    readTime: "6 min",
    searchTerms: "effective versus headline rate jurisdictions worked example",
  },
  {
    number: "№ 14",
    date: "Mar 6, 2026",
    title: "Your first cross-border filing, step by step",
    dek: "The practical walkthrough for founders facing two tax authorities for the first time. No jargon.",
    topic: "Compliance",
    region: "Global",
    access: "free",
    readTime: "9 min",
    searchTerms: "first cross border filing step by step guide",
  },
  {
    number: "№ 13",
    date: "Feb 27, 2026",
    title: "Tonnage tax: why shipping plays by its own rules",
    dek: "An entire industry taxed on the size of its ships, not its profit. How the strangest regime in tax works.",
    topic: "Tax Economics",
    region: "Global",
    access: "premium",
    readTime: "7 min",
    searchTerms: "tonnage tax shipping special deal flags",
  },
  {
    number: "№ 12",
    date: "Feb 20, 2026",
    title: "The country that taxes you wherever you live",
    dek: "America taxes its citizens on worldwide income — for life, anywhere. The expat's unavoidable headache.",
    topic: "Cross-Border",
    region: "Americas",
    access: "free",
    readTime: "7 min",
    searchTerms: "us citizenship based taxation expats fatca",
  },
];

export const FEATURED_ISSUE = ISSUES[0];
export const LIST_ISSUES = ISSUES.slice(1);
